import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const inter = Roboto({ weight: ["400", "500", "700"], subsets: ['latin'] })

import Header from '@/components/Header/Header'

export const metadata: Metadata = {
  title: 'Minute Math',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url("/bg.png")] bg-no-repeat bg-cover bg-center h-screen`}>
        <Header />
        <main className='contianer'>{children}</main>
      </body>
    </html>
  )
}
