import './globals.css'
import type { Metadata } from 'next'
import { Overpass } from 'next/font/google'

const inter = Overpass({ subsets: ['latin'] })

import Header from '@/components/Header/Header'

export const metadata: Metadata = {
  title: 'Minute Math',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <main className='contianer'>{children}</main>
      </body>
    </html>
  )
}
