import './globals.css'
import type { Metadata } from 'next'
import { Overpass } from 'next/font/google'

import bg from '../assets/math-bg.png'

const inter = Overpass({ subsets: ['latin'] })

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

export const metadata: Metadata = {
  title: 'Minute Math',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url("/math-bg.png")] bg-no-repeat bg-cover h-screen`}>
        <Header />
        <main className='contianer'>{children}</main>
      </body>
    </html>
  )
}
